theme: jekyll-theme-cayman
title: Bulk Crap Uninstaller - Remove large amounts of unwanted applications
description: Bulk Crap Uninstaller (BCUninstaller, BCU) is a free, open source program manager. It excels at removing large amounts of applications with minimal user input.
