version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: bulk-uninstaller
    path: ./.cspell/bulk-uninstaller.txt
    addWords: true
dictionaries:
  - bulk-uninstaller
words: []
ignoreWords: []
import: []
