#
# Espanso - WinGet Workflow
#

name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get Version
        id: get-version
        run: |
          # Finding the version from release name
          $VERSION = '${{ github.event.release.tag_name }}'.Replace('v', $Null) + '.0.0'
          echo "version=$VERSION" >> $GITHUB_STATE
        shell: pwsh

      - uses: vedantmgoyal2009/winget-releaser@v2
        name: WinGet Release
        with:
          identifier: Klocman.BulkCrapUninstaller
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
